---
name: actionlint
on:
  pull_request:
    branches: [main]
    paths:
    - .github/**
    - aqua/actionlint.yaml
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aquaproj/aqua-installer@v3.0.1
      with:
        aqua_version: v2.25.1
    - uses: suzuki-shunsuke/github-action-actionlint@v0.1.3
