---
name: Hide comments
on:
  pull_request:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: read
  pull-requests: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v2.1.1
        with:
         aqua_version: v2.5.2
      - run: github-comment exec -- github-comment hide
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
