---
name: Hide comments
on:
  pull_request:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: read
  pull-requests: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v2.3.2
        with:
         aqua_version: v2.25.0
      - run: github-comment exec -- github-comment hide
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
